### ISSUE TITLE
WTForms 1.0.5 doesn't work with Python 3.8

### ISSUE THREAD

**Issue by mlenzen** [mlenzen/wtforms-sqlalchemy#2]
The tests specify testing against WTForms 1.0.5 which breaks in Python 3.8.

https://travis-ci.org/mlenzen/wtforms-sqlalchemy/builds/630103264

```
ERROR: tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests
Traceback (most recent call last):
  File "/opt/python/3.8.0/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/travis/build/mlenzen/wtforms-sqlalchemy/tests/tests.py", line 13, in <module>
    from wtforms.compat import text_type, iteritems
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/wtforms/__init__.py", line 11, in <module>
    from wtforms import validators, widgets
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/wtforms/widgets/__init__.py", line 1, in <module>
    from wtforms.widgets.core import *
  File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/wtforms/widgets/core.py", line 3, in <module>
    from cgi import escape
ImportError: cannot import name 'escape' from 'cgi' (/opt/python/3.8.0/lib/python3.8/cgi.py)
```

Options are:
* drop support for WTForms 1.0.5 (released in 2013)
* exclude the bad jobs
* enumerate all options in the testing matrix

See: https://docs.travis-ci.com/user/build-matrix/
